

services:
  db:
    image: postgres:13
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build: .
    command: >
      bash -c "/wait-for-it db:${DATABASE_PORT} -- alembic upgrade head"  # Ждем базу и применяем миграции
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db  # Alembic должен подождать, пока база будет доступна
    volumes:
      - .:/app

  web:
    build: .
    ports:
      - "${PORT}:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - alembic  # Web-приложение запускается только после завершения миграций
    volumes:
      - .:/app
    command: python run.py  # Запуск приложения после миграций

"""  init_password:
    build: .
    command: python password.py  # Запуск скрипта для добавления админа
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - web  # Ждем, пока веб-приложение будет запущено
    volumes:
      - .:/app"""

volumes:
  postgres_data:
