version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build: .
    command: >
      bash -c "/wait-for-it db:${DATABASE_PORT} -- alembic upgrade head"  # Ждем базу и применяем миграции
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - .:/app

  web:
    build: .
    ports:
      - "${PORT}:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - alembic
      - redis  # Убедитесь, что веб-приложение ждет Redis
    volumes:
      - .:/app
    command: python run.py  # Запуск приложения после миграций

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A celery_worker.app worker --loglevel=info
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

  flower:
    image: mher/flower
    command: ["celery", "-A", "app_celery.celery", "flower", "--address=0.0.0.0", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
