services:
  db:
    image: postgres:13
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 40s  # Увеличьте интервал
      timeout: 20s
      retries: 15  # Увеличьте количество попыток
    networks:
      - stts-dev_app_network

  alembic:
    build: .
    command: bash -c "alembic upgrade head"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "bash", "-c", "alembic current | grep -q 'head'"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - stts-dev_app_network

  web:
    build: .
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"  
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HTTP_PROXY=http://localhost:80
      - HTTPS_PROXY=https://localhost:443
      - SSL_CERT_FILE=/app/certs/fullchain.pem
      - SSL_KEY_FILE=/app/certs/privkey.pem

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - ./certs:/app/certs:ro
    command: python run.py
    #network_mode: "host"
    networks:
      - stts-dev_app_network


  init_password:
    build: .
    command: python password.py  # Запуск скрипта для добавления админа
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - stts-dev_app_network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stts-dev_app_network

volumes:
  postgres_data:

networks:
  stts-dev_app_network:
    external: true

