"""фгвшщ срфтпуы

Revision ID: 00c2ac182bbc
Revises: 80796f7ff1a8
Create Date: 2024-11-13 14:18:59.441876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c2ac182bbc'
down_revision: Union[str, None] = '80796f7ff1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('url', sa.String(length=255), nullable=True))
    op.alter_column('audio_files', 'bucket_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('audio_files', 's3_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_files', 's3_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('audio_files', 'bucket_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('audio_files', 'url')
    # ### end Alembic commands ###
