"""Transcribed flag

Revision ID: 03a9209bb46a
Revises: a1aec2e0862d
Create Date: 2024-11-08 10:54:31.760972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a9209bb46a'
down_revision: Union[str, None] = 'a1aec2e0862d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_analysis', 'analysis', type_='foreignkey')
    op.drop_constraint('fk_user_api_keys', 'api_keys', type_='foreignkey')
    op.add_column('audio_files', sa.Column('transcribed', sa.Boolean()))
    op.drop_constraint('fk_user_audio_files', 'audio_files', type_='foreignkey')
    op.drop_constraint('fk_user_prompts', 'prompts', type_='foreignkey')
    op.drop_constraint('fk_user_transcriptions', 'transcriptions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_user_transcriptions', 'transcriptions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_prompts', 'prompts', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_audio_files', 'audio_files', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('audio_files', 'transcribed')
    op.create_foreign_key('fk_user_api_keys', 'api_keys', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_user_analysis', 'analysis', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
